spring:
  application:
    name: project-BEC-unigap
  datasource:
    url: 'jdbc:mysql://localhost:3306/job_db'
    username: root
    password: 21012004VIEt@
  cache:
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: 21012004Viet

redis:
  cache-names:
    - name: employersList
      ttl: 2
    - name: jobsList
      ttl: 1

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

sentry:
  dsn: "https://fa069c646642dd2d259e0343c1109e0d@o4507739248132096.ingest.de.sentry.io/4507739317862480"

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}