spring:
  application:
    name: project-BEC-unigap
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/job_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  cache:
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      username: ${SPRING_DATA_MONGODB_USERNAME:}
      password: ${SPRING_DATA_MONGODB_PASSWORD:}
      database: ${SPRING_DATA_MONGODB_DATABASE:job_db}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

redis:
  cache-names:
    - name: employersList
      ttl: 2
    - name: jobsList
      ttl: 1

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

sentry:
  dsn: ${SENTRY_DSN}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  chat-id: ${TELEGRAM_CHAT_ID:}