spring:
  application:
    name: project-BEC-unigap
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/job_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  cache:
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

redis:
  cache-names:
    - name: employersList
      ttl: 2
    - name: jobsList
      ttl: 1

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

sentry:
  dsn: ${SENTRY_DSN}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  chat-id: ${TELEGRAM_CHAT_ID:}